"""Pipeline code generation — export transform history as production-ready code.

Supported output formats:
- polars: Standalone Python script using Polars
- sql: DuckDB-compatible SQL statements
- dbt: dbt model SQL file with config block
- script: Minimal Python script (no function wrapper)
"""

from __future__ import annotations

from datetime import datetime, timezone

from .transforms import TransformStep


def generate_pipeline(
    steps: list[TransformStep],
    *,
    format: str = "polars",
    source: str | None = None,
    output: str | None = None,
    name: str | None = None,
    description: str | None = None,
    schema: dict[str, str] | None = None,
) -> str:
    """Generate production-ready pipeline code from transform steps.

    Args:
        steps: List of TransformStep objects from workspace history.
        format: Output format — 'polars', 'sql', 'dbt', or 'script'.
        source: Source file path (for comments/loader).
        output: Output file path (for export line).
        name: Pipeline/model name.
        description: Description comment.
        schema: Input schema dict (column → type).

    Returns:
        Generated code string.

    Raises:
        ValueError: If format is not recognized.
    """
    generators = {
        "polars": _generate_polars,
        "sql": _generate_sql,
        "dbt": _generate_dbt,
        "script": _generate_script,
    }

    generator = generators.get(format)
    if generator is None:
        raise ValueError(
            f"Unknown format: '{format}'. Available: {', '.join(generators.keys())}"
        )

    return generator(
        steps,
        source=source,
        output=output,
        name=name,
        description=description,
        schema=schema,
    )


def _generate_polars(
    steps: list[TransformStep],
    *,
    source: str | None = None,
    output: str | None = None,
    name: str | None = None,
    description: str | None = None,
    schema: dict[str, str] | None = None,
) -> str:
    """Generate a production-ready Polars Python script.

    Wraps transforms in a `transform()` function with type annotations,
    adds a `__main__` block for standalone execution.
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    func_name = _sanitize_name(name) if name else "transform"

    lines: list[str] = []

    # Header comment
    lines.append(f'"""Pipeline generated by Sweet on {now}.')
    if description:
        lines.append(f"\n{description}")
    if source:
        lines.append(f"\nSource: {source}")
    lines.append('"""')
    lines.append("")
    lines.append("import polars as pl")
    lines.append("")
    lines.append("")

    # Transform function
    lines.append(f"def {func_name}(df: pl.DataFrame) -> pl.DataFrame:")
    if description:
        lines.append(f'    """{description}"""')

    if not steps:
        lines.append("    return df")
    else:
        # Build chained expression
        chain_lines = _build_polars_chain(steps)
        if len(chain_lines) == 1:
            lines.append(f"    df = {chain_lines[0]}")
        else:
            lines.append("    df = (")
            lines.append(f"        {chain_lines[0]}")
            for chain_line in chain_lines[1:]:
                lines.append(f"        {chain_line}")
            lines.append("    )")
        lines.append("    return df")

    lines.append("")
    lines.append("")

    # Main block
    lines.append('if __name__ == "__main__":')
    if source:
        ext = source.rsplit(".", 1)[-1] if "." in source else "csv"
        reader = _polars_reader(ext)
        lines.append(f'    df = {reader}("{source}")')
    else:
        lines.append('    df = pl.read_csv("input.csv")  # TODO: set input path')

    lines.append(f"    result = {func_name}(df)")

    if output:
        ext = output.rsplit(".", 1)[-1] if "." in output else "csv"
        writer = _polars_writer(ext)
        lines.append(f'    result.{writer}("{output}")')
    else:
        lines.append('    result.write_parquet("output.parquet")')

    lines.append("")

    return "\n".join(lines)


def _generate_script(
    steps: list[TransformStep],
    *,
    source: str | None = None,
    output: str | None = None,
    name: str | None = None,
    description: str | None = None,
    schema: dict[str, str] | None = None,
) -> str:
    """Generate a minimal script (no function wrapper)."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    lines: list[str] = []

    # Header
    lines.append(f"# Generated by Sweet on {now}")
    if description:
        lines.append(f"# {description}")
    lines.append("")
    lines.append("import polars as pl")
    lines.append("")

    # Load
    if source:
        ext = source.rsplit(".", 1)[-1] if "." in source else "csv"
        reader = _polars_reader(ext)
        lines.append(f'df = {reader}("{source}")')
    else:
        lines.append('df = pl.read_csv("input.csv")  # TODO: set input path')
    lines.append("")

    # Steps
    for i, step in enumerate(steps):
        desc = step.metadata.get("description", "") if step.metadata else ""
        if desc:
            lines.append(f"# Step {i + 1}: {desc}")
        expr = step.expr
        if expr.startswith("df = "):
            lines.append(expr)
        else:
            lines.append(f"df = {expr}")
        lines.append("")

    # Export
    if output:
        ext = output.rsplit(".", 1)[-1] if "." in output else "csv"
        writer = _polars_writer(ext)
        lines.append(f'df.{writer}("{output}")')
    else:
        lines.append('df.write_parquet("output.parquet")')
    lines.append("")

    return "\n".join(lines)


def _generate_sql(
    steps: list[TransformStep],
    *,
    source: str | None = None,
    output: str | None = None,
    name: str | None = None,
    description: str | None = None,
    schema: dict[str, str] | None = None,
) -> str:
    """Generate DuckDB-compatible SQL from transform steps.

    Converts Polars expressions to SQL equivalents where possible.
    Falls back to comments for complex expressions.
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    lines: list[str] = []
    lines.append(f"-- Generated by Sweet on {now}")
    if description:
        lines.append(f"-- {description}")
    lines.append("")

    # Source table
    table_name = name or "result"
    if source:
        lines.append(f"-- Source: {source}")
        source_ref = f"read_csv_auto('{source}')"
    else:
        source_ref = "source_table"
    lines.append("")

    # Convert each step to SQL or comment
    sql_steps = _polars_to_sql_steps(steps, source_ref)

    if sql_steps:
        # Use CTEs for multi-step
        if len(sql_steps) == 1:
            lines.append(f"CREATE OR REPLACE TABLE {table_name} AS")
            lines.append(f"{sql_steps[0]};")
        else:
            lines.append(f"CREATE OR REPLACE TABLE {table_name} AS")
            lines.append("WITH")
            for i, (sql, comment) in enumerate(sql_steps[:-1]):
                cte_name = f"step_{i + 1}"
                lines.append(f"  -- {comment}" if comment else "")
                lines.append(f"  {cte_name} AS (")
                lines.append(f"    {sql}")
                lines.append("  ),")
            # Final step
            last_sql, last_comment = sql_steps[-1]
            if last_comment:
                lines.append(f"  -- {last_comment}")
            lines.append(last_sql + ";")
    else:
        lines.append(f"-- No SQL-convertible steps. Source: {source_ref}")
        lines.append(f"SELECT * FROM {source_ref};")

    lines.append("")
    return "\n".join(lines)


def _generate_dbt(
    steps: list[TransformStep],
    *,
    source: str | None = None,
    output: str | None = None,
    name: str | None = None,
    description: str | None = None,
    schema: dict[str, str] | None = None,
) -> str:
    """Generate a dbt model SQL file."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    model_name = name or "stg_transformed"

    lines: list[str] = []

    # dbt config block
    lines.append("{{")
    lines.append("  config(")
    lines.append("    materialized='table',")
    if description:
        lines.append(f"    description='{description}',")
    lines.append("  )")
    lines.append("}}")
    lines.append("")
    lines.append(f"-- Generated by Sweet on {now}")
    lines.append(f"-- Model: {model_name}")
    lines.append("")

    # Source reference
    if source:
        source_ref = "{{ source('raw', '" + source.rsplit("/", 1)[-1].rsplit(".", 1)[0] + "') }}"
    else:
        source_ref = "{{ source('raw', 'source_table') }}"

    # Convert steps
    sql_steps = _polars_to_sql_steps(steps, source_ref)

    if sql_steps and len(sql_steps) > 1:
        lines.append("WITH")
        for i, (sql, comment) in enumerate(sql_steps[:-1]):
            cte_name = f"step_{i + 1}"
            if comment:
                lines.append(f"-- {comment}")
            lines.append(f"{cte_name} AS (")
            lines.append(f"  {sql}")
            comma = "," if i < len(sql_steps) - 2 else ""
            lines.append(f"){comma}")
            lines.append("")
        last_sql, last_comment = sql_steps[-1]
        if last_comment:
            lines.append(f"-- {last_comment}")
        lines.append(last_sql)
    elif sql_steps:
        sql, comment = sql_steps[0]
        if comment:
            lines.append(f"-- {comment}")
        lines.append(sql)
    else:
        lines.append(f"SELECT * FROM {source_ref}")

    lines.append("")
    return "\n".join(lines)


# =============================================================================
# Helpers
# =============================================================================


def _build_polars_chain(steps: list[TransformStep]) -> list[str]:
    """Build a chained Polars expression from steps.

    Tries to collapse sequential operations into a chain.
    """
    chain_parts: list[str] = []

    for step in steps:
        expr = step.expr.strip()
        # Strip "df = " prefix if present
        if expr.startswith("df = "):
            expr = expr[5:]
        # Strip leading "df." to allow chaining
        if expr.startswith("df."):
            chain_parts.append("." + expr[3:])
        else:
            # Can't chain — starts a new expression
            if chain_parts:
                chain_parts[-1] = chain_parts[-1]  # keep as-is
            chain_parts.append(expr)

    if not chain_parts:
        return ["df"]

    # If all parts are chainable (start with .)
    if all(p.startswith(".") for p in chain_parts):
        result = ["df"]
        result.extend(chain_parts)
        return result

    # Otherwise return as separate assignments
    return [f"df{p}" if p.startswith(".") else p for p in chain_parts]


def _polars_to_sql_steps(
    steps: list[TransformStep], source_ref: str
) -> list[tuple[str, str]]:
    """Best-effort conversion of Polars steps to SQL.

    Returns list of (sql_string, comment) tuples.
    """
    results: list[tuple[str, str]] = []
    prev_ref = source_ref

    for step in steps:
        expr = step.expr.strip()
        desc = step.metadata.get("description", "") if step.metadata else ""

        # Strip df prefix
        if expr.startswith("df = "):
            expr = expr[5:]
        if expr.startswith("df."):
            expr = expr[3:]

        sql = _expr_to_sql(expr, prev_ref)
        if sql:
            results.append((sql, desc))
            prev_ref = f"step_{len(results)}" if len(results) < 20 else prev_ref

    return results


def _expr_to_sql(expr: str, source: str) -> str | None:
    """Convert a single Polars expression to SQL (best effort).

    Returns SQL string or None if not convertible.
    """
    # filter(condition)
    if expr.startswith("filter(") and expr.endswith(")"):
        condition = expr[7:-1]
        sql_cond = _polars_condition_to_sql(condition)
        if sql_cond:
            return f"SELECT * FROM {source} WHERE {sql_cond}"

    # select([...]) or select(...)
    if expr.startswith("select("):
        cols = _extract_column_names(expr)
        if cols:
            return f"SELECT {', '.join(cols)} FROM {source}"

    # unique()
    if expr == "unique()":
        return f"SELECT DISTINCT * FROM {source}"

    # sort(...)
    if expr.startswith("sort("):
        cols = _extract_sort_columns(expr)
        if cols:
            return f"SELECT * FROM {source} ORDER BY {cols}"

    # head(n) / limit
    if expr.startswith("head(") and expr.endswith(")"):
        n = expr[5:-1]
        return f"SELECT * FROM {source} LIMIT {n}"

    # Generic with_columns — add as comment
    if expr.startswith("with_columns("):
        return f"SELECT *, /* {expr} */ FROM {source}"

    # Fallback: wrap in comment
    return f"SELECT * FROM {source} /* polars: {expr} */"


def _polars_condition_to_sql(condition: str) -> str | None:
    """Convert a Polars filter condition to SQL WHERE clause."""
    # pl.col('x') > 5 → x > 5
    import re

    # Simple pl.col('name') op value patterns
    pattern = r"pl\.col\(['\"](\w+)['\"]\)\s*(>|<|>=|<=|==|!=)\s*(.+)"
    match = re.match(pattern, condition.strip())
    if match:
        col, op, val = match.groups()
        sql_op = "=" if op == "==" else ("<>" if op == "!=" else op)
        return f"{col} {sql_op} {val}"

    # pl.col('x').is_not_null()
    pattern_not_null = r"pl\.col\(['\"](\w+)['\"]\)\.is_not_null\(\)"
    match = re.match(pattern_not_null, condition.strip())
    if match:
        return f"{match.group(1)} IS NOT NULL"

    # pl.col('x').is_null()
    pattern_null = r"pl\.col\(['\"](\w+)['\"]\)\.is_null\(\)"
    match = re.match(pattern_null, condition.strip())
    if match:
        return f"{match.group(1)} IS NULL"

    return None


def _extract_column_names(expr: str) -> list[str] | None:
    """Extract column names from a select expression."""
    import re

    # Match quoted column names
    cols = re.findall(r'["\'](\w+)["\']', expr)
    return cols if cols else None


def _extract_sort_columns(expr: str) -> str | None:
    """Extract sort column specification."""
    import re

    # Match sort('col') or sort('col', descending=True)
    cols = re.findall(r'["\'](\w+)["\']', expr)
    if not cols:
        return None
    desc = "descending=True" in expr or "descending = True" in expr
    suffix = " DESC" if desc else ""
    return ", ".join(f"{c}{suffix}" for c in cols)


def _polars_reader(ext: str) -> str:
    """Get the Polars reader function for a file extension."""
    readers = {
        "csv": "pl.read_csv",
        "parquet": "pl.read_parquet",
        "json": "pl.read_json",
        "jsonl": "pl.read_ndjson",
        "ndjson": "pl.read_ndjson",
        "ipc": "pl.read_ipc",
        "avro": "pl.read_avro",
        "xlsx": "pl.read_excel",
        "xls": "pl.read_excel",
    }
    return readers.get(ext, "pl.read_csv")


def _polars_writer(ext: str) -> str:
    """Get the Polars writer method for a file extension."""
    writers = {
        "csv": "write_csv",
        "parquet": "write_parquet",
        "json": "write_json",
        "jsonl": "write_ndjson",
        "ndjson": "write_ndjson",
        "ipc": "write_ipc",
        "avro": "write_avro",
        "xlsx": "write_excel",
    }
    return writers.get(ext, "write_csv")


def _sanitize_name(name: str) -> str:
    """Convert a name to a valid Python identifier."""
    import re

    name = re.sub(r"[^a-zA-Z0-9_]", "_", name)
    name = re.sub(r"_+", "_", name).strip("_").lower()
    if name and name[0].isdigit():
        name = "fn_" + name
    return name or "transform"
