"""Tests for sweet.core.codegen — pipeline code generation."""

from __future__ import annotations

import pytest

from sweet.core.codegen import generate_pipeline, _sanitize_name
from sweet.core.transforms import TransformStep


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


def _step(expr: str, desc: str = "") -> TransformStep:
    """Create a minimal TransformStep for testing."""
    return TransformStep(
        expr=expr,
        input_hash="abc123",
        output_schema=None,
        metadata={"description": desc} if desc else {},
    )


SAMPLE_STEPS = [
    _step("df.filter(pl.col('age') > 18)", "Filter adults"),
    _step("df.select(['name', 'age'])", "Select columns"),
    _step("df.sort('age')", "Sort by age"),
]


# ---------------------------------------------------------------------------
# Format: polars
# ---------------------------------------------------------------------------


class TestPolarsFormat:
    def test_basic_generation(self):
        code = generate_pipeline(SAMPLE_STEPS, format="polars")
        assert "import polars as pl" in code
        assert "def transform(" in code
        assert 'if __name__ == "__main__"' in code

    def test_custom_name(self):
        code = generate_pipeline(SAMPLE_STEPS, format="polars", name="clean_data")
        assert "def clean_data(" in code
        assert "clean_data(df)" in code

    def test_source_path(self):
        code = generate_pipeline(SAMPLE_STEPS, format="polars", source="data.csv")
        assert 'pl.read_csv("data.csv")' in code
        assert "Source: data.csv" in code

    def test_source_parquet(self):
        code = generate_pipeline(SAMPLE_STEPS, format="polars", source="data.parquet")
        assert 'pl.read_parquet("data.parquet")' in code

    def test_output_path(self):
        code = generate_pipeline(SAMPLE_STEPS, format="polars", output="out.parquet")
        assert 'write_parquet("out.parquet")' in code

    def test_output_csv(self):
        code = generate_pipeline(SAMPLE_STEPS, format="polars", output="out.csv")
        assert 'write_csv("out.csv")' in code

    def test_description(self):
        code = generate_pipeline(SAMPLE_STEPS, format="polars", description="My pipeline")
        assert "My pipeline" in code

    def test_empty_steps(self):
        code = generate_pipeline([], format="polars")
        assert "return df" in code
        assert "import polars" in code

    def test_contains_timestamp(self):
        code = generate_pipeline(SAMPLE_STEPS, format="polars")
        assert "Pipeline generated by Sweet on" in code


# ---------------------------------------------------------------------------
# Format: script
# ---------------------------------------------------------------------------


class TestScriptFormat:
    def test_basic_generation(self):
        code = generate_pipeline(SAMPLE_STEPS, format="script")
        assert "import polars as pl" in code
        assert "# Generated by Sweet on" in code
        # No function wrapper
        assert "def " not in code

    def test_steps_as_assignments(self):
        code = generate_pipeline(SAMPLE_STEPS, format="script")
        assert "df = " in code

    def test_step_descriptions(self):
        code = generate_pipeline(SAMPLE_STEPS, format="script")
        assert "# Step 1: Filter adults" in code
        assert "# Step 2: Select columns" in code
        assert "# Step 3: Sort by age" in code

    def test_source_path(self):
        code = generate_pipeline(SAMPLE_STEPS, format="script", source="input.json")
        assert 'pl.read_json("input.json")' in code

    def test_output_path(self):
        code = generate_pipeline(SAMPLE_STEPS, format="script", output="result.csv")
        assert 'write_csv("result.csv")' in code

    def test_default_output(self):
        code = generate_pipeline(SAMPLE_STEPS, format="script")
        assert 'write_parquet("output.parquet")' in code


# ---------------------------------------------------------------------------
# Format: sql
# ---------------------------------------------------------------------------


class TestSqlFormat:
    def test_basic_generation(self):
        code = generate_pipeline(SAMPLE_STEPS, format="sql")
        assert "-- Generated by Sweet on" in code
        assert "CREATE OR REPLACE TABLE" in code

    def test_custom_name(self):
        code = generate_pipeline(SAMPLE_STEPS, format="sql", name="cleaned")
        assert "CREATE OR REPLACE TABLE cleaned AS" in code

    def test_source_ref(self):
        code = generate_pipeline(SAMPLE_STEPS, format="sql", source="data.csv")
        assert "read_csv_auto('data.csv')" in code

    def test_filter_conversion(self):
        steps = [_step("df.filter(pl.col('age') > 18)", "Filter adults")]
        code = generate_pipeline(steps, format="sql")
        assert "WHERE age > 18" in code

    def test_select_conversion(self):
        steps = [_step("df.select(['name', 'age'])", "Pick columns")]
        code = generate_pipeline(steps, format="sql")
        assert "SELECT name, age FROM" in code

    def test_unique_conversion(self):
        steps = [_step("df.unique()", "Deduplicate")]
        code = generate_pipeline(steps, format="sql")
        assert "SELECT DISTINCT *" in code

    def test_sort_conversion(self):
        steps = [_step("df.sort('age')", "Sort")]
        code = generate_pipeline(steps, format="sql")
        assert "ORDER BY age" in code

    def test_head_conversion(self):
        steps = [_step("df.head(10)", "Take top 10")]
        code = generate_pipeline(steps, format="sql")
        assert "LIMIT 10" in code

    def test_description(self):
        code = generate_pipeline(SAMPLE_STEPS, format="sql", description="Transform pipeline")
        assert "-- Transform pipeline" in code

    def test_empty_steps(self):
        code = generate_pipeline([], format="sql")
        assert "No SQL-convertible steps" in code


# ---------------------------------------------------------------------------
# Format: dbt
# ---------------------------------------------------------------------------


class TestDbtFormat:
    def test_basic_generation(self):
        code = generate_pipeline(SAMPLE_STEPS, format="dbt")
        assert "config(" in code
        assert "materialized='table'" in code
        assert "-- Generated by Sweet on" in code

    def test_custom_name(self):
        code = generate_pipeline(SAMPLE_STEPS, format="dbt", name="stg_users")
        assert "-- Model: stg_users" in code

    def test_source_reference(self):
        code = generate_pipeline(SAMPLE_STEPS, format="dbt", source="raw/users.csv")
        assert "{{ source('raw', 'users') }}" in code

    def test_description_in_config(self):
        code = generate_pipeline(SAMPLE_STEPS, format="dbt", description="Users staging")
        assert "description='Users staging'" in code

    def test_empty_steps(self):
        code = generate_pipeline([], format="dbt")
        assert "SELECT * FROM" in code


# ---------------------------------------------------------------------------
# Error handling
# ---------------------------------------------------------------------------


class TestErrors:
    def test_unknown_format(self):
        with pytest.raises(ValueError, match="Unknown format: 'xml'"):
            generate_pipeline(SAMPLE_STEPS, format="xml")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


class TestSanitizeName:
    def test_basic(self):
        assert _sanitize_name("hello world") == "hello_world"

    def test_special_chars(self):
        assert _sanitize_name("my-pipeline!v2") == "my_pipeline_v2"

    def test_leading_digit(self):
        assert _sanitize_name("123test") == "fn_123test"

    def test_empty(self):
        assert _sanitize_name("") == "transform"

    def test_already_valid(self):
        assert _sanitize_name("clean_data") == "clean_data"


# ---------------------------------------------------------------------------
# Integration: Workspace.generate_pipeline()
# ---------------------------------------------------------------------------


class TestWorkspaceIntegration:
    def test_generate_pipeline_from_workspace(self, tmp_path):
        import polars as pl

        from sweet.core.workspace import Workspace

        # Create a temp CSV
        csv_file = tmp_path / "test.csv"
        df = pl.DataFrame({"name": ["Alice", "Bob"], "age": [30, 17]})
        df.write_csv(csv_file)

        ws = Workspace()
        ws.load(str(csv_file))
        ws.transform("df.filter(pl.col('age') > 18)")

        code = ws.generate_pipeline(format="polars", source=str(csv_file))
        assert "import polars as pl" in code
        assert "def transform(" in code
        assert "filter" in code

    def test_all_formats_produce_output(self, tmp_path):
        import polars as pl

        from sweet.core.workspace import Workspace

        csv_file = tmp_path / "data.csv"
        pl.DataFrame({"x": [1, 2, 3]}).write_csv(csv_file)

        ws = Workspace()
        ws.load(str(csv_file))
        ws.transform("df.filter(pl.col('x') > 1)")

        for fmt in ("polars", "sql", "dbt", "script"):
            code = ws.generate_pipeline(format=fmt)
            assert len(code) > 20, f"Format '{fmt}' produced too little output"
